//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.MyNorthwindGeneralService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyNorthwindGeneralService.IGeneralService")]
    public interface IGeneralService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetCustomerCount", ReplyAction="http://tempuri.org/IGeneralService/GetCustomerCountResponse")]
        int GetCustomerCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetCustomerCount", ReplyAction="http://tempuri.org/IGeneralService/GetCustomerCountResponse")]
        System.Threading.Tasks.Task<int> GetCustomerCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetProductCount", ReplyAction="http://tempuri.org/IGeneralService/GetProductCountResponse")]
        int GetProductCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetProductCount", ReplyAction="http://tempuri.org/IGeneralService/GetProductCountResponse")]
        System.Threading.Tasks.Task<int> GetProductCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralServiceChannel : MyNorthwindGeneralService.IGeneralService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralServiceClient : System.ServiceModel.ClientBase<MyNorthwindGeneralService.IGeneralService>, MyNorthwindGeneralService.IGeneralService {
        
        public GeneralServiceClient() {
        }
        
        public GeneralServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCustomerCount() {
            return base.Channel.GetCustomerCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCustomerCountAsync() {
            return base.Channel.GetCustomerCountAsync();
        }
        
        public int GetProductCount() {
            return base.Channel.GetProductCount();
        }
        
        public System.Threading.Tasks.Task<int> GetProductCountAsync() {
            return base.Channel.GetProductCountAsync();
        }
    }
}
