//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.MyNorthwindRegionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://schemas.datacontract.org/2004/07/NorthwindDAL", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Region : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionDescription {
            get {
                return this.RegionDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionDescriptionField, value) != true)) {
                    this.RegionDescriptionField = value;
                    this.RaisePropertyChanged("RegionDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionID {
            get {
                return this.RegionIDField;
            }
            set {
                if ((this.RegionIDField.Equals(value) != true)) {
                    this.RegionIDField = value;
                    this.RaisePropertyChanged("RegionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyNorthwindRegionService.IRegionService")]
    public interface IRegionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionService/GetRegions", ReplyAction="http://tempuri.org/IRegionService/GetRegionsResponse")]
        MyNorthwindRegionService.Region[] GetRegions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegionService/GetRegions", ReplyAction="http://tempuri.org/IRegionService/GetRegionsResponse")]
        System.Threading.Tasks.Task<MyNorthwindRegionService.Region[]> GetRegionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegionServiceChannel : MyNorthwindRegionService.IRegionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegionServiceClient : System.ServiceModel.ClientBase<MyNorthwindRegionService.IRegionService>, MyNorthwindRegionService.IRegionService {
        
        public RegionServiceClient() {
        }
        
        public RegionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyNorthwindRegionService.Region[] GetRegions() {
            return base.Channel.GetRegions();
        }
        
        public System.Threading.Tasks.Task<MyNorthwindRegionService.Region[]> GetRegionsAsync() {
            return base.Channel.GetRegionsAsync();
        }
    }
}
